% \iffalse meta-comment
%
% hmcthesisposter.cls -- LaTeX shim class for creating posters
% 
% Copyright (C) 2008 Claire M. Connelly and 
% the Department of Mathematics, Harvey Mudd College
% 
% This program is free software; you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation; either version 2 of the License, or
% (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
% 
% Contact: Claire Connelly <cmc@math.hmc.edu>
%          Department of Mathematics
%          Harvey Mudd College
%          1250 N. Dartmouth Ave.
%          Claremont, CA 91711
%
% $Id: hmcthesisposter.cls 278 2008-04-21 19:22:31Z cmc $
% 
% \fi
%%
%% HMC Poster Shim LaTeX class file.
%%

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{hmcthesisposter}[2008/04/21 Shim Poster Class]

\ClassError{hmcthesisposter}{This document class is obsolete;\MessageBreak
  use the hmcposter document class instead.}{%
Update your LaTeX source file to use\MessageBreak
  \noexpand\documentclass[thesis]{hmcposter}\MessageBreak
  and typeset it again.}

\endinput
